<?php
// This file is automatically generated by ci4-attribute-routes.
// Please do not modify this file.
$routes->get('bbs/index', '\App\Controllers\Bbs::index');
$routes->get('bbs/post', '\App\Controllers\Bbs::post');
$routes->post('bbs/confirm', '\App\Controllers\Bbs::confirm');
$routes->post('bbs/delete/(:num)', '\App\Controllers\Bbs::delete/$1');
$routes->post('bbs/insert', '\App\Controllers\Bbs::insert');
$routes->get('form', '\App\Controllers\Form::index');
$routes->post('form', '\App\Controllers\Form::index');
$routes->post('form/confirm', '\App\Controllers\Form::confirm');
$routes->post('form/send', '\App\Controllers\Form::send');
$routes->post('shop/add/(:num)', '\App\Controllers\Shop\Cart::add/$1');
$routes->get('shop/cart', '\App\Controllers\Shop\Cart::index');
$routes->post('shop/customer_info', '\App\Controllers\Shop\CustomerInfo::index');
$routes->post('shop/confirm', '\App\Controllers\Shop\CustomerInfo::confirm');
$routes->get('shop/index/(:num)', '\App\Controllers\Shop\Index::index/$1');
$routes->get('shop/index/(:num)/(:num)', '\App\Controllers\Shop\Index::index/$1/$2');
$routes->post('shop/order', '\App\Controllers\Shop\Order::index');
$routes->get('shop/product/(:num)', '\App\Controllers\Shop\Product::index/$1');
$routes->get('shop/search', '\App\Controllers\Shop\Search::index');
$routes->get('shop/search/(:num)', '\App\Controllers\Shop\Search::index/$1');
